# -*- coding: utf-8 -*-
"""PGD 3nd Home Work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBYm46iVkdWVO6bdFfxRogmlTt_1nKWb
"""

n=int(input("Input upper limit: "))
print(f"Natural numbers from 1 to {n}:",end=" ")
i=1
while i<=n:
  print(i,end=",")
  i+=1

n=int(input("Input N: "))
print(f"Natural numbers from {n}-1 in reverse: ",end=" ")
for i in range(n,0,-1):
  print(i,end=",")

letters="abcdefghijklmnopqrstuvwxyz"
print("Alphabets:", end=" ")
for i in range(len(letters)):
  print(letters[i],end=",")

n=int(input("Input upper range: "))
print(f"Natural numbers from 1 to {n}:")
for i in range(2,12,2):
  print(i,end=",")
  i+=2

n = int(input("Input upper range: "))
print(f"Even numbers between 1 to {n}:")
for i in range(1, n + 1):
    if i % 2 == 0:
        print(i, end=", " if i < n else "\n")

n = int(input("Input upper range: "))
print(f"Even numbers between 1 to {n}:")
for i in range(1, n + 1):
    if i % 2 != 0:
        print(i, end=", ")

n=int(input("Input upper limit: "))
sum=0
for i in range(1,n+1):
  sum+=i
print(f"Natural numbers from 1 to {n}:",sum)

n=int(input("Input upper limit of even number: "))
sum=0
for i in range(1,n+1):
  if i%2==0:
    sum+=i
print(f"Sum of even numbers between 1 to {n}:",sum)

n=int(input("Input upper limit: "))
sum=0
for i in range(1,n+1):
  if i%2!=0:
    sum+=i
print(f"Sum of odd numbers from 1-{n}:",sum)

n=int(input("Input num: "))
for i in range(1,11):
  print(f"{n} * {i} = {n*i}")

n=int(input("Input num: "))
count=0
tem=abs(n)
for i in range(0, len(str(tem))):
  count+=1
print("Number of digits:", count)

num = int(input("Input number: "))
temp = abs(num)
last_digit = temp % 10
while temp >= 10:
    temp //= 10
first_digit = temp
print("First digit:", first_digit)
print("Last digit:", last_digit)

num=int(input("Input number: "))
temp=abs(num)
last_digit=temp%10
while temp>=10:
  temp//=10
  first_digit=temp
sum=first_digit+last_digit
print("Sum of first and last digit:",sum)

num=int(input("Input any number: "))
temp = abs(num)
digits = len(str(temp))
last_digit = temp % 10
first_digit = temp // (10 ** (digits - 1))
middle = temp % (10 ** (digits - 1))
middle = middle // 10
swapped = (last_digit * (10 ** (digits - 1))) + (middle * 10) + first_digit
if num < 0:
    swapped = -swapped
print("Number after swapping first and last digit:", swapped)

num=int(input("Input any number: "))
sum=0
for i in str(num):
  sum+=int(i)
print("Sum of digits: ",sum)

num=int(input("Input number: "))
product=1
for i in str(num):
  product*=int(i)
print("Product of digits: ",product)

num=input("Input number: ")
b=num[::-1]
print(f"Reverse of 12345 =",b)

num = int(input("Input number: "))
temp = abs(num)
reverse = 0
while temp > 0:
    reverse = reverse * 10 + (temp % 10)
    temp //= 10
if num < 0:
    reverse = -reverse
print("Reverse of", num, "=", reverse)

num = int(input("Input any number: "))
original = num
temp = abs(num)
reverse = 0
while temp != 0:
    digit = temp % 10
    reverse = reverse * 10 + digit
    temp //= 10
if num < 0:
    reverse = -reverse
if num == reverse:
    print(num, "is palindrome")
else:
    print(num, "is not palindrome")

num = input("Input any number: ")
num = num.replace("-", "")
print("Digit frequency in", num, ":")
for i in range(10):
    count = num.count(str(i))
    if count > 0:
        print("Digit", i, "=>", count, "times")

num = input("Input number: ")
num_words = {
    '0': 'Zero',
    '1': 'One',
    '2': 'Two',
    '3': 'Three',
    '4': 'Four',
    '5': 'Five',
    '6': 'Six',
    '7': 'Seven',
    '8': 'Eight',
    '9': 'Nine'
}
for i in num:
    if i in num_words:
        print(num_words[digit], end=" ")

for i in range(256):
    print(f"ASCII value of character {chr(i)} = {i}")

num1=int(input("Input base: "))
num2=int(input("Input exponent: "))
c=num1**num2
print("2 ^ 5 =",c)

base = int(input("Input base: "))
exponent = int(input("Input exponent: "))
result = 1
for i in range(exponent):
    result *= base
print(f"{base} ^ {exponent} = {result}")

num=int(input("Input number: "))
print("Factors of",num,":",end=" ")
for i in range(1,num+1):
  if num%i==0:
    print(i,end=" ")

num=int(input("Input number: "))
factorial=1
for i in range(1,num+1):
    factorial*=i
print("Factorial: ",factorial)

num1=int(input("Input first number: "))
num2=int(input("Input second number: "))
for i in range(1,min(num1,num2)+1):
  if num1%i==0 and num2%i==0:
    hcf=i
print("HCF of 12 and 30: ",hcf)

num1 = int(input("Input number1: "))
num2 = int(input("Input number2: "))
if num1 > num2:
    greater = num1
else:
    greater = num2
for i in range(greater, (num1 * num2) + 1):
    if (i % num1 == 0) and (i % num2 == 0):
        lcm = i
        break
print("LCM =", lcm)

num = int(input("Input any number: "))
if num < 2:
    print(f"{num} is not prime number")
else:
    for i in range(2, num):
        if num % i == 0:
            print(f"{num} is not prime number")
            break
    else:
        print(f"{num} is prime number")

lower = int(input("Input lower limit: "))
upper = int(input("Input upper limit: "))
print(f"Prime numbers between {lower}-{upper}:", end=" ")
for num in range(lower, upper + 1):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num, end=" ")

lower = int(input("Input lower limit: "))
upper = int(input("Input upper limit: "))
total=0
for num in range(lower, upper + 1):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            total+=num
print("\nSum of prime numbers between 1-10: ",total)

num = int(input("Input any number: "))
n = num
print(f"Prime factors of {num}:", end=" ")
i = 2
while i <= n:
    if n % i == 0:
        print(i, end=" ")
        n = n // i
    else:
        i += 1

num = int(input("Input number: "))
num_str = str(num)
num_digits = len(num_str)
sum_of_digits = 0
for digit in num_str:
    sum_of_digits += int(digit) ** num_digits
if sum_of_digits == num:
    print(f"{num} is armstrong number")
else:
    print(f"{num} is not armstrong number")

lower = int(input("Enter lower limit: "))
upper = int(input("Enter upper limit: "))
print(f"Armstrong number between {lower} to {upper} are:", end=" ")
for num in range(lower, upper + 1):
    num_str = str(num)
    num_digits = len(num_str)
    sum_of_digits = 0
    for digit in num_str:
        sum_of_digits += int(digit) ** num_digits
    if sum_of_digits == num:
        print(num, end=",")

num= int(input("Input any number: "))
sum=0
for i in range(1,num):
  if num%i==0:
    sum+=i
if sum == num:
    print(f"{num} is PERFECT NUMBER")
else:
  print(f"{num} is not PERFECT NUMBER")

upper = int(input("Input upper limit: "))
print(f"Perfect numbers between 1 and {upper}:", end=" ")
for num in range(1, upper + 1):
    sum_of_divisors = 0
    for i in range(1, num):
        if num % i == 0:
            sum_of_divisors += i
    if sum_of_divisors == num:
        print(num, end=",")

num = int(input("Input number: "))
temp = num
sum_of_factorials = 0
while temp > 0:
    digit = temp % 10
    fact = 1
    for i in range(1, digit + 1):
        fact *= i
    sum_of_factorials += fact
    temp //= 10
if sum_of_factorials == num:
    print(f"{num} is STRONG NUMBER")
else:
    print(f"{num} is not a Strong Number")

upper = int(input("Input upper limit: "))
print(f"Strong numbers between 1-{num}:", end=" ")
for num in range(1, upper + 1):
    temp = num
    sum_of_factorials = 0
    while temp > 0:
        digit = temp % 10
        fact = 1
        for i in range(1, digit + 1):
            fact *= i
        sum_of_factorials += fact
        temp //= 10
    if sum_of_factorials == num:
        print(num, end=",")

n = int(input("Input number of terms: "))
a, b = 0, 1
print("Fibonacci series:", end=" ")
for i in range(n):
    print(a, end=",")
    c = a + b
    a = b
    b = c

binary = input("Input binary number: ")
ones_complement = ""
for bit in binary:
    if bit == '0':
        ones_complement += '1'
    elif bit == '1':
        ones_complement += '0'
    else:
        print("Invalid binary number")
        exit()
print("Ones complement:", ones_complement)

binary = input("Input binary number: ")
ones_complement = ""
for bit in binary:
    if bit == '0':
        ones_complement += '1'
    elif bit == '1':
        ones_complement += '0'
    else:
        print("Invalid binary number")
        exit()
twos_complement = ""
carry = 1
for bit in reversed(ones_complement):
    if bit == '1' and carry == 1:
        twos_complement = '0' + twos_complement
        carry = 1
    elif bit == '0' and carry == 1:
        twos_complement = '1' + twos_complement
        carry = 0
    else:
        twos_complement = bit + twos_complement

print("Twos complement:", twos_complement)

binary = input("Input binary number: ")
decimal = int(binary, 2)
octal = oct(decimal)[2:]
print("Octal number:", octal)

