# -*- coding: utf-8 -*-
"""PGD-2nd Home Work.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCy3__zZyMsyOOYO0u7gd1ApnvX2zF6X

**Sl No-01**
"""

num1=int(input("Input num1: "))
num2=int(input("Input num2: "))
if num1>num2:
  print(f"Maximum = {num1}")
else:
  print(f"Maximum = {num2}")

"""**Sl No-02**"""

num1=int(input("Input num1: "))
num2=int(input("Input num2: "))
num3=int(input("Input num3: "))
if num1>num2 and num1>num3:
  print(f"Maximum is: {num1}")
elif num2>num3:
  print(f"Maximum is: {num2}")
else:
  print(f"Maximum is: {num3}")

"""**Sl No-03**"""

num1=int(input("Input number: "))
if num1>=0:
  print(f"{num1} is positive")
else:
  print(f"{num1} is negative")

"""**Sl No-04**"""

num1=int(input("Input number: "))
if num1%5==0 and num1%11==0:
  print(f"Number is divided by 5 and 11")
else:
  print(f"Number is not divided by 5 and 11")

"""**Sl No-05**"""

num1=int(input("Input number: "))
if num1%2==0:
  print(f"{num1} is even number")
else:
  print(f"{num1} is odd number")

"""**Sl No-06**"""

year=int(input("Input year: "))
if year%4==0:
  print(f"{year} is leap year.")
else:
  print(f"{year} is not leap year.")

"""**Sl No-07**"""

ch=input("Input character: ")
if ((ch in "abcdefghijklmnopqrstuvwxyz") or (ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ")):
  print(f"'{ch}' is alphabet")
else:
  print(f"'{ch}' is not alphabet")

"""**Alternative Option**"""

ch = input("Input character: ")
if ch.isalpha():
    print(f"'{ch}' is alphabet")
else:
    print(f"'{ch}' is not alphabet")

"""**Sl No-08**"""

ch=input("Input character: ")
if (ch in "aeiou") or (ch in "AEIOU"):
  print(f"'{ch}' is vowel")
else:
  print(f"'{ch}' is not vowel")

"""**Sl No-09**"""

ch=input("Input any character: ")
if ch.isalpha():
  print(f"{ch} is alphabet")
elif ch>='0' and ch<='9':
  print(f"{ch} is digit")
else:
  print(f"{ch} is special character")

"""**Sl No-10**"""

ch=input("Input character: ")
if ch.isupper():
  print(f"'{ch}'is uppercase alphabet")
elif ch.islower():
  print(f"'{ch}'is lowercase alphabet")
else:
  print(f"'{ch}'is not alphabet")

"""**Sl No-11**"""

week=int(input("Input week number: "))
if week==1:
  print("Monday")
elif week==2:
  print("Tuesday")
elif week==3:
  print("Wednesday")
elif week==4:
  print("Thursday")
elif week==5:
  print("Friday")
elif week==6:
  print("Saturday")
elif week==7:
  print("Sunday")
else:
  print("Invalid week number")

"""**Sl No-12**"""

month=int(input("Enter month number: "))
if month==1:
  print("It contains 31 days.")
elif month==2:
  print("It contains 28 days.")
elif month==3:
  print("It contains 31 days.")
elif month==4:
  print("It contains 30 days.")
elif month==5:
  print("It contains 31 days.")
elif month==6:
  print("It contains 30 days.")
elif month==7:
  print("It contains 31 days.")
elif month==8:
  print("It contains 31 days.")
elif month==9:
  print("It contains 30 days.")
elif month==10:
  print("It contains 31 days.")
elif month==11:
  print("It contains 30 days.")
elif month==12:
  print("It contains 31 days.")
else:
  print("Invalid month number")

"""**Sl No-13**"""

amount=int(input("Input amount: "))
n500 = n100 = n50 = n20 = n10 = n5 = n2 = n1 = 0
if amount >= 500:
    n500 = amount // 500
    amount = amount % 500
if amount >= 100:
    n100 = amount // 100
    amount = amount % 100
if amount >= 50:
    n50 = amount // 50
    amount = amount % 50
if amount >= 20:
    n20 = amount // 20
    amount = amount % 20
if amount >= 10:
    n10 = amount // 10
    amount = amount % 10
if amount >= 5:
    n5 = amount // 5
    amount = amount % 5
if amount >= 2:
    n2 = amount // 2
    amount = amount % 2
if amount >= 1:
    n1 = amount // 1
    amount = amount % 1
print("\nTotal number of notes:")
print("500:", n500)
print("100:", n100)
print("50 :", n50)
print("20 :", n20)
print("10 :", n10)
print("5  :", n5)
print("2  :", n2)
print("1  :", n1)

"""**Sl No-14**"""

angle1=int(input("Input first angle: "))
angle2=int(input("Input second angle: "))
angle3=int(input("Input third angle: "))
if angle1+angle2+angle3==180:
  print("The triangle is valid")
else:
  print("The triangle is not valid")

"""**Sl No-15**"""

side1=int(input("Input first side: "))
side2=int(input("Input second side: "))
side3=int(input("Input third side: "))
if (side1+side2>side3) and (side1+side3>side2) and (side2+side3>side1):
  print("Triangle is valid")
else:
  print("Triangle is not valid")

"""**Sl No-16**"""

side1=int(input("Input first side: "))
side2=int(input("input second side: "))
side3=int(input("input third side: "))
if side1==side2==side3:
  print(f"Triangle is equilateral triangle")
elif side1==side2 or side1==side3 or side2==side3:
  print(f"Triangle is isosceles triangle")
else:
  print(f"Triangle is scalene triangle")

"""**Sl No-17**"""

import math

# Input coefficients
a = float(input("Input a: "))
b = float(input("Input b: "))
c = float(input("Input c: "))

# Calculate discriminant
D = b*b - 4*a*c

# Check conditions using if...else
if D > 0:
    root1 = (-b + math.sqrt(D)) / (2*a)
    root2 = (-b - math.sqrt(D)) / (2*a)
    print(f"Root1: {root1:.2f}")
    print(f"Root2: {root2:.2f}")

elif D == 0:
    root = -b / (2*a)
    print(f"Root1 = Root2 = {root:.2f}")

else:
    # For complex roots
    real_part = -b / (2*a)
    imag_part = math.sqrt(-D) / (2*a)
    print(f"Root1: {real_part:.2f} + {imag_part:.2f}i")
    print(f"Root2: {real_part:.2f} - {imag_part:.2f}i")

"""**Sl No-18**"""

price1=int(input("Input cost price: "))
price2=int(input("Input selling price: "))
if price2>price1:
  profit=price2-price1
  print(f"Profit: {profit}")
else:
  loss=price1-price2
  print(f"Loss: {loss}")

"""**Sl No-19**"""

print(f"Input marks of five subjects: ")
marks = [float(input()) for _ in range(5)]
total = sum(marks)
percentage = (total / 500) * 100
if percentage >= 90:
    grade = 'A'
elif percentage >= 80:
    grade = 'B'
elif percentage >= 70:
    grade = 'C'
elif percentage >= 60:
    grade = 'D'
elif percentage >= 40:
    grade = 'E'
else:
    grade = 'F'
print(f"\nPercentage = {percentage:.2f}")
print(f"Grade {grade}")

print("Input marks of five subjects:")
m1 = float(input())
m2 = float(input())
m3 = float(input())
m4 = float(input())
m5 = float(input())
total = m1 + m2 + m3 + m4 + m5
percentage = (total / 500) * 100
if percentage >= 90:
    grade = 'A'
elif percentage >= 80:
    grade = 'B'
elif percentage >= 70:
    grade = 'C'
elif percentage >= 60:
    grade = 'D'
elif percentage >= 40:
    grade = 'E'
else:
    grade = 'F'
print(f"\nPercentage = {percentage:.2f}")
print(f"Grade {grade}")

"""**Sl No-20**"""

basic = float(input("Input basic salary of an employee: "))
if basic <= 10000:
    hra = basic * 0.20
    da = basic * 0.80
elif basic <= 20000:
    hra = basic * 0.25
    da = basic * 0.90
else:
    hra = basic * 0.30
    da = basic * 0.95

gross = basic + hra + da
print(f"\nGross salary = {gross:.0f}")

"""**Sl No-21**"""

units = float(input("Enter total units consumed: "))
if units <= 50:
    amount = units * 0.50
elif units <= 150:
    amount = (50 * 0.50) + ((units - 50) * 0.75)
elif units <= 250:
    amount = (50 * 0.50) + (100 * 0.75) + ((units - 150) * 1.20)
else:
    amount = (50 * 0.50) + (100 * 0.75) + (100 * 1.20) + ((units - 250) * 1.50)
surcharge = amount * 0.20
total_bill = amount + surcharge
print(f"\nElectricity Bill = Rs. {total_bill:.2f}")